/* eslint-disable global-require */
export default {
  alessi: require('../images/AlessiAv.png'),
  anne: require('../images/AnneAv.png'),
  anubis: require('../images/AnubisAv.png'),
  arabia: require('../images/ArabiaFatsAv.png'),
  avdol: require('../images/AvdolAv.png'),
  boingo: require('../images/BoingoAv.png'),
  cameo: require('../images/CameoAv.png'),
  chaka: require('../images/ChakaAv.png'),
  darby: require('../images/DArbyAv.png'),
  devo: require('../images/DevoAv.png'),
  dio: require('../images/DIOAv.png'),
  enya: require('../images/EnyaAv.png'),
  forever: require('../images/ForeverAv.png'),
  geil: require('../images/GeilAv.png'),
  gray: require('../images/GrayFlyAv.png'),
  holHorse: require('../images/HolHorseAv.png'),
  holy: require('../images/HolyAv.png'),
  iggy: require('../images/IggyAv.png'),
  jotaro: require('../images/JotaroAv.png'),
  kakyoin: require('../images/KakyoinAv.png'),
  kenny: require('../images/KennyAv.png'),
  khan: require('../images/KhanAv.png'),
  malena: require('../images/MalenaAv.png'),
  mannish: require('../images/MannishBoyAv.png'),
  mariah: require('../images/MariahAv.png'),
  midler: require('../images/MidlerAv.png'),
  // eslint-disable-next-line quotes
  ndoul: require("../images/N'DoulAv.png"),
  nena: require('../images/NenaAv.png'),
  nukesaku: require('../images/NukesakuAv.png'),
  oingo: require('../images/OingoAv.png'),
  joseph: require('../images/OldJosephAv.png'),
  petShop: require('../images/PetShopAv.png'),
  polnareff: require('../images/PolnareffAv.png'),
  roses: require('../images/RosesAv.png'),
  rubberSoul: require('../images/RubberSoulAv.png'),
  sherry: require('../images/SherryAv.png'),
  steelyDan: require('../images/SteelyDanAv.png'),
  suziQ: require('../images/SuziQAv.png'),
  telence: require('../images/TelenceAv.png'),
  tennille: require('../images/TennilleAv.png'),
  vanilllaIce: require('../images/VanillaIceAv.png'),
  wilson: require('../images/WilsonPhillipsAv.png'),
  zz: require('../images/ZZAv.png'),
};
